language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist --diff --dry-run
  - ./vendor/bin/phpstan
  - composer test
